### ISSUE TITLE
[bug] failed compiling in docker container

### ISSUE THREAD

**Issue by xial-thu** [NVIDIA/go-nvml#8] opened 2021-02-01 02:26 UTC
I wrote a simple unit test and I found that the test goes well on **bare-metal**, but fails compiling in container.

To make sure I have available GPUs in container:

```
$ echo $NVIDIA_VISIBLE_DEVICES
GPU-4b41ce77-8c75-e9e7-b631-36b3c0d52c51,GPU-40bada99-59cd-67b6-9b77-724f00f0222d

$ nvidia-smi
Mon Feb  1 10:18:53 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:09.0 Off |                    0 |
| N/A   41C    P0    43W / 300W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:00:0A.0 Off |                    0 |
| N/A   41C    P0    45W / 300W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

$ ll /dev/nvidia*
crw-rw-rw- 1 root root 195,   4 Jan 14 19:36 /dev/nvidia4
crw-rw-rw- 1 root root 195,   5 Jan 14 19:36 /dev/nvidia5
crw-rw-rw- 1 root root 195, 255 Jan 14 19:36 /dev/nvidiactl
crw-rw-rw- 1 root root 233,   0 Jan 14 19:36 /dev/nvidia-uvm
crw-rw-rw- 1 root root 233,   1 Jan 14 19:36 /dev/nvidia-uvm-tools
```

When running the test in container, it reports:

> $ go test ./pkg/util
> # github.com/NVIDIA/go-nvml/pkg/nvml
> ../.go/pkg/mod/github.com/!n!v!i!d!i!a/go-nvml@v0.0.0-20201208210537-1c123dad9d48/pkg/nvml/nvml.go:282:16: could not determine kind of name for C.nvmlAffinityScope_t
> ../.go/pkg/mod/github.com/!n!v!i!d!i!a/go-nvml@v0.0.0-20201208210537-1c123dad9d48/pkg/nvml/nvml.go:1936:16: could not determine kind of name for C.nvmlBlacklistDeviceInfo_t
> ../.go/pkg/mod/github.com/!n!v!i!d!i!a/go-nvml@v0.0.0-20201208210537-1c123dad9d48/pkg/nvml/nvml.go:2075:11: could not determine kind of name for C.nvmlComputeInstanceDestroy
> ../.go/pkg/mod/github.com/!n!v!i!d!i!a/go-nvml@v0.0.0-20201208210537-1c123dad9d48/pkg/nvml/nvml.go:2105:11: could not determine kind of name for C.nvmlComputeInstanceGetInfo
> ../.go/pkg/mod/github.com/!n!v!i!d!i!a/go-nvml@v0.0.0-20201208210537-1c123dad9d48/pkg/nvml/nvml.go:2104:16: could not determine kind of name for C.nvmlComputeInstanceInfo_t
> ../.go/pkg/mod/github.com/!n!v!i!d!i!a/go-nvml@v0.0.0-20201208210537-1c123dad9d48/pkg/nvml/nvml.go:2046:16: could not determine kind of name for C.nvmlComputeInstanceProfileInfo_t
> ../.go/pkg/mod/github.com/!n!v!i!d!i!a/go-nvml@v0.0.0-20201208210537-1c123dad9d48/pkg/nvml/nvml.go:2066:27: could not determine kind of name for C.nvmlComputeInstance_t
> ../.go/pkg/mod/github.com/!n!v!i!d!i!a/go-nvml@v0.0.0-20201208210537-1c123dad9d48/pkg/nvml/nvml.go:1475:19: could not determine kind of name for C.nvmlDetachGpuState_t
> ...(the same as above, a lot of error messages)

I guess it's due to either missing libs when pass-through GPU to container, or the go-binding itself has some problems. As a dev-ops engineer, I'm not fimiliar with GPU, so would you help explain why I cannot call the libs in container, thx!

The source code of my test:

```go
func TestGetGPUStatus(t *testing.T) {
	ret := nvml.Init()
	if ret != nvml.SUCCESS {
		t.Error(ret.Error())
	}
	defer func() {
		if ret := nvml.Shutdown(); ret != nvml.SUCCESS {
			t.Error(ret.Error())
		}
	}()

	n, ret := nvml.DeviceGetCount()
	if ret != nvml.SUCCESS {
		t.Error(ret.Error())
	}
	for i := 0; i < n; i++ {
		dev, ret := nvml.DeviceGetHandleByIndex(i)
		if ret != nvml.SUCCESS {
			t.Error(ret.Error())
		}
		_, ret = dev.GetUUID()
		if ret != nvml.SUCCESS {
			t.Error(ret.Error())
		}

		_, ret = dev.GetName()
		if ret != nvml.SUCCESS {
			t.Error(ret.Error())
		}

		_, ret = dev.GetMemoryInfo()
		if ret != nvml.SUCCESS {
			t.Error(ret.Error())
		}

		_, ret = dev.GetUtilizationRates()
		if ret != nvml.SUCCESS {
			t.Error(ret.Error())
		}
	}
}
```

**Comment by elezar** [comment] 2021-02-01 09:09
Which container are you using and how are you launching it? NVML needs access to the devices and the drivers which need to be present in the running container. Depending on you setup there are different ways to achieve this. Are you able to launch GPU-enabled containers in general?

**Comment by klueska** [comment] 2021-02-01 09:44
This looks as though the C header is not getting picked up during compilation. How did you run `go mod vendor` to pull the package into a vendor folder, or just `go mod` to pull it into your host level GOPATH?

It's hard to tell with the strange path of:
```
../.go/pkg/mod/github.com/!n!v!i!d!i!a/go-nvml/...
```

In any case, do you see a `nvml.h` file in the `/pkg/nvml/` folder? It that's missing, that would explain this.

That said, it would be strange if it's missing, since I have used `go mod` many times with `go-nvml` without problems. MAybe an older version of `go mod` strips out C header files?

**Comment by xial-thu** [comment] 2021-02-02 05:23
> Which container are you using and how are you launching it? NVML needs access to the devices and the drivers which need to be present in the running container. Depending on you setup there are different ways to achieve this. Are you able to launch GPU-enabled containers in general?

I'm using nvidia-container-runtime. I started the container by kubernetes(default runtime is nv-container-runtime) by specifying resource: `nvidia.com/gpu: 2`.

All the AI workloads, such as pytorch jobs... work well. But I'm not able to compile this code.

I guess the drivers are properly mounted into the container, `nvidia-smi` works and see below output:

```bash
$ ll /dev/nvidia*
crw-rw-rw- 1 root root 195,   4 Jan 14 19:36 /dev/nvidia4
crw-rw-rw- 1 root root 195,   5 Jan 14 19:36 /dev/nvidia5
crw-rw-rw- 1 root root 195, 255 Jan 14 19:36 /dev/nvidiactl
crw-rw-rw- 1 root root 233,   0 Jan 14 19:36 /dev/nvidia-uvm
crw-rw-rw- 1 root root 233,   1 Jan 14 19:36 /dev/nvidia-uvm-tools
```

Or any other ways to verify the driver capability?

**Comment by xial-thu** [comment] 2021-02-02 05:30
> This looks as though the C header is not getting picked up during compilation. How did you run `go mod vendor` to pull the package into a vendor folder, or just `go mod` to pull it into your host level GOPATH?
> 
> It's hard to tell with the strange path of:
> 
> ```
> ../.go/pkg/mod/github.com/!n!v!i!d!i!a/go-nvml/...
> ```
> 
> In any case, do you see a `nvml.h` file in the `/pkg/nvml/` folder? It that's missing, that would explain this.
> 
> That said, it would be strange if it's missing, since I have used `go mod` many times with `go-nvml` without problems. MAybe an older version of `go mod` strips out C header files?

Oh I did not run `go mod vendor`, just using go module, like:

```
module xxx

go 1.15

require (
	github.com/NVIDIA/go-nvml v0.0.0-20201208210537-1c123dad9d48
```

The strange `../.go/pkg` is due to my `GOPATH` setting, to dig out if nvml.h exists, here's the output:

```bash
$ ls ../.go/pkg/mod/github.com/\!n\!v\!i\!d\!i\!a/go-nvml@v0.0.0-20201208210537-1c123dad9d48/pkg/nvml/nvml.h
../.go/pkg/mod/github.com/!n!v!i!d!i!a/go-nvml@v0.0.0-20201208210537-1c123dad9d48/pkg/nvml/nvml.h
```

go version: 

```bash
$ go version
go version go1.15.6 linux/amd64
```

Any ideas?

**Comment by klueska** [comment] 2021-02-04 09:51
Nothing obvious jumps out as to why it wouldn't work. Can you try vendoring it in your build environment and see if that helps?

**Comment by aerok** [comment] 2021-06-23 07:49
```
➜  go-nvml git:(master) ✗ make test
c-for-go -out /home/aerok/workspace/go-nvml/pkg /home/aerok/workspace/go-nvml/gen/nvml/nvml.yml
  processing /home/aerok/workspace/go-nvml/gen/nvml/nvml.yml done.
cp /home/aerok/workspace/go-nvml/gen/nvml/*.go /home/aerok/workspace/go-nvml/pkg/nvml
cd /home/aerok/workspace/go-nvml/pkg/nvml; \
	go tool cgo -godefs types.go > types_gen.go; \
	go fmt types_gen.go; \
cd -> /dev/null
types_gen.go
rm -rf /home/aerok/workspace/go-nvml/pkg/nvml/types.go /home/aerok/workspace/go-nvml/pkg/nvml/_obj
grep -l -R "// WARNING: This file has automatically been generated on" pkg \
	| xargs sed -i -E 's#// WARNING: This file has automatically been generated on.*$#// WARNING: THIS FILE WAS AUTOMATICALLY GENERATED.#g'
grep -l -RE "// (.*) nvml/nvml.h:[0-9]+" pkg \
	| xargs sed -i -E 's#// (.*) nvml/nvml.h:[0-9]+$#// \1 nvml/nvml.h#g'
cd /home/aerok/workspace/go-nvml/pkg/nvml; \
	go test -v .; \
cd -> /dev/null
# github.com/NVIDIA/go-nvml/pkg/nvml [github.com/NVIDIA/go-nvml/pkg/nvml.test]
./device.go:25:29: undefined: Return
./device.go:32:49: undefined: Return
./device.go:39:54: undefined: Return
./device.go:46:50: undefined: Return
./device.go:53:58: undefined: Return
./device.go:60:44: undefined: Return
./device.go:66:41: undefined: Return
./device.go:71:37: undefined: BrandType
./device.go:71:48: undefined: Return
./types_gen.go:9:10: undefined: _Ctype_struct_nvmlDevice_st
./device.go:71:48: too many errors
FAIL	github.com/NVIDIA/go-nvml/pkg/nvml [build failed]
FAIL
➜  go-nvml git:(master) ✗ tree .
.
├── CONTRIBUTING.md
├── Dockerfile
├── gen
│   └── nvml
│       ├── cgo_helpers.go
│       ├── const_gen.go
│       ├── device.go
│       ├── event_set.go
│       ├── init.go
│       ├── nvml.h
│       ├── nvml_test.go
│       ├── nvml.yml
│       ├── return.go
│       ├── system.go
│       ├── unit.go
│       └── vgpu.go
├── go.mod
├── go.sum
├── LICENSE
├── Makefile
├── pkg
│   ├── dl
│   │   ├── dl.go
│   │   └── dl_test.go
│   └── nvml
│       ├── cgo_helpers.go
│       ├── cgo_helpers.h
│       ├── const_gen.go
│       ├── const.go
│       ├── device.go
│       ├── doc.go
│       ├── event_set.go
│       ├── init.go
│       ├── nvml.go
│       ├── nvml.h
│       ├── nvml_test.go
│       ├── return.go
│       ├── system.go
│       ├── types_gen.go
│       ├── unit.go
│       └── vgpu.go
└── README.md

5 directories, 37 files

```

**Comment by elezar** [comment] 2021-06-23 07:59
@aerok your error seems different to the one originally reported in this issue. Are you also seeing this failure in a container?  If not could you please create a separate issue and provide additional information on your development environment.

**Comment by xial-thu** [comment] 2021-06-23 08:21
@elezar @klueska  It's frustrating that this go-binding does not work in container. I found another one, https://github.com/mindprince/gonvml, that works. But that one provides limited API and does not cover all of my demands. Sadly I'm not fimiliar with CGo so I can't figure out the differences.

Do you have any plan on supporting compiling go-nvml in container? Container is cloud-computing engineer's oxygen, many of us are using container everywhere: develop, test, debug, build, release... To use this project, we have to do it on bare-metal, and it is so frustrating...

**Comment by elezar** [comment] 2021-06-23 08:36
@xial-thu we use the bindings in packages that are built in containers on a regular basis and have not come across this behaviour ourselves. It should be noted that we **always** vendor in the dependencies and use up to date go versions. This could be the difference.

If you are able to provide a sample `Dockerfile` that reproduces the issues that you are seeing we could debug this further. We will also look at the project you linked and see if there is anything apparent that we are missing on our end.

**Comment by xial-thu** [comment] 2021-06-24 06:52
> @xial-thu we use the bindings in packages that are built in containers on a regular basis and have not come across this behaviour ourselves. It should be noted that we **always** vendor in the dependencies and use up to date go versions. This could be the difference.
> 
> If you are able to provide a sample `Dockerfile` that reproduces the issues that you are seeing we could debug this further. We will also look at the project you linked and see if there is anything apparent that we are missing on our end.

Several months ago, I do met the problem, but now I cannot reproduce it now. It works well... Same code, same go mod (not vendor), same nvidia driver and gpu product, the only difference is that my pod shifts to another host.

If I reproduce this issue some day, I'll update this issue. Now please close this issue.

BTW, why do you always vendor? Is there any difference between go module and vendor?

**Comment by elezar** [comment] 2021-06-24 11:28
Thanks for the update. I'll close the issue then.

With regards to:
> BTW, why do you always vendor? Is there any difference between go module and vendor?

This means that our dependencies are all checked into version control and don't need to be pulled in when building (e.g. in containers). This makes the builds of container images, for example, a little bit quicker and means that we can more easily build on systems without public internet access directly from the repo.

In theory, however, there should't be a significant difference in behaviour when pulling dependencies in at build time (as I believe these are generally cached anyway).

**Closed by elezar** 2021-06-24 11:28 UTC
